language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -e .[testing]
  - pip install coveralls

# commands to run tests
script:
  - pytest --cov manga_saver --cov-branch

after_success:
  - coveralls

notifications:
  email: false